### ISSUE TITLE
findmessages.py不能使用

### ISSUE THREAD

**Issue by neko039** [isu-cisa/isu-credential#12]
findmessages.py程式沒有改過，現在程式不能跑了，這裡的BUNDLE是去抓dashboard頁面上的
![image](https://user-images.githubusercontent.com/69495937/93851911-9c671b00-fce3-11ea-991f-ec5c1741c5c9.png)

錯誤訊息:

hello bundle is : KDEUKSKBHGIJKWVULZNEVYIRUBXUJWXIWJLQRAEPDCSAHHBHTDNHRSPJYFKOSXCPCDESBQYXQVEGEEDGB
Transaction =  {'hashes': [], 'duration': 0}
Transaction hash =  
Traceback (most recent call last):
  File "findmessages.py", line 23, in <module>
    print(findmessages(TXN_BUNDLE))
  File "findmessages.py", line 16, in findmessages
    bundle = api.get_bundles(test)
  File "/home/iota_server02/.local/lib/python3.6/site-packages/iota/api.py", line 721, in get_bundles
    return extended.GetBundlesCommand(self.adapter)(transaction=transaction)
  File "/home/iota_server02/.local/lib/python3.6/site-packages/iota/commands/__init__.py", line 126, in __call__
    replacement = self._prepare_request(self.request)
  File "/home/iota_server02/.local/lib/python3.6/site-packages/iota/commands/__init__.py", line 300, in _prepare_request
    failure_message = 'Request failed validation',
  File "/home/iota_server02/.local/lib/python3.6/site-packages/iota/commands/__init__.py", line 335, in _apply_filter
    'filter_errors': runner.get_errors(with_context=True),
ValueError: Request failed validation ({'transaction': ['empty']}) (`exc.context["filter_errors"]` contains more information).

**Comment by neko039** [comment]
別人新丟上去的BUNDLE是可以找到的
![image](https://user-images.githubusercontent.com/69495937/93851555-ed2a4400-fce2-11ea-9c49-74dc6b0589e0.png)

python3 findmessages.py 
hello bundle is : TCDQXUT9E9WJL9LKLJBSDVFNLAYQ9HHGMIJLAIWDMHZYERPHLLLGIHMJCWQWCGIDDMNCLJJUUGKB9VZMD
Transaction =  {'hashes': [TransactionHash(b'UNLFOAQDJSKDXLUHEWVFHRYAVXBSTGANXUFUIXCXESSXAWGGUKMKGZUWOSXNAPCK9BV9XZORFRTIA9999')], 'duration': 0}
Transaction hash =  UNLFOAQDJSKDXLUHEWVFHRYAVXBSTGANXUFUIXCXESSXAWGGUKMKGZUWOSXNAPCK9BV9XZORFRTIA9999
Travetown-Spamming
Count: 082617
Timestamp: 2020-09-22T08:41:23+02:00
gTTA took 0s

去抓原本在dashboard的BUNDLE去找的，就不行了

**Comment by yillkid** [comment]
## 錯誤畫面
![image](https://user-images.githubusercontent.com/185872/95810273-220a4380-0d43-11eb-8dc3-c53d0934cb90.png)

## 分析
1. 這是因為所屬的 full-node 被 snapshot 了，早期的交易全部被清除
2. 即便找不到對應的 credentials 也不該直接顯示 error message page

## 解決方案
- [x] 就算因為帳本完整度問題，導致 findTransaction API 返回空值，也不能讓頁面崩潰
  - ![image](https://user-images.githubusercontent.com/185872/95818235-f9d81000-0d55-11eb-8e3d-bd69091a088a.png)

- [ ] 調整 permanode，讓所有的帳本恢復
